package com.sas.mobile.xpathsource;

/** *** DO NOT EDIT THIS FILE ***<br>
    THIS FILE IS GENERATED AUTOMATICALLY by org.safs ComponentGenerator jar!<br><p> **/
 

public final class map_mbi_android {


    // The Names of Window and Child Component objects: 

    /** "Report" Component and its children. */
    public static class Report {

        // No use for a default constructor.
        private Report(){}

        /** "Report" Window Component itself. */
        public static final String Report = new String("Report");

        /** "report_Menu_ShareReport" String in "Report". */
        public static final String report_Menu_ShareReport ="//android.view.View[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[2]/android.widget.ImageButton[1]";

        /** "report_Menu_Update" String in "Report". */
        public static final String report_Menu_Update ="//android.view.View[1]/android.widget.FrameLayout[2]/android.view.View[1]/android.widget.RelativeLayout[1]/android.widget.ScrollView[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[1]/android.widget.Button[1]";

        /** "report_SidePanel_AddComment" String in "Report". */
        public static final String report_SidePanel_AddComment ="//android.view.View[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[3]/android.widget.TextView[3]";

        /** "report_Menu_Properties" String in "Report". */
        public static final String report_Menu_Properties ="//android.view.View[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[1]";

        /** "report_Menu_AnnotationSection" String in "Report". */
        public static final String report_Menu_AnnotationSection ="//android.widget.ListView[1]/android.widget.CheckedTextView[1]";

        /** "report_Close" String in "Report". */
        public static final String report_Close ="//android.widget.ListView[1]/android.widget.LinearLayout[1]/android.widget.RelativeLayout[1]/android.widget.TextView[1]";

        /** "report_Menu" String in "Report". */
        public static final String report_Menu ="//android.view.View[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[3]/android.widget.TextView[2]";

        /** "report_Menu_ViewSource" String in "Report". */
        public static final String report_Menu_ViewSource ="//android.view.View[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]";

        /** "report_SidePanel_Reminder" String in "Report". */
        public static final String report_SidePanel_Reminder ="//android.view.View[1]/android.widget.FrameLayout[2]/android.view.View[1]/android.widget.RelativeLayout[1]/android.widget.ScrollView[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[2]/android.widget.LinearLayout[1]/android.widget.Button[1]";

        /** "report_SidePanel" String in "Report". */
        public static final String report_SidePanel ="//android.view.View[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[3]/android.widget.TextView[1]";

        /** "report_TotalOfContent" String in "Report". */
        public static final String report_TotalOfContent ="//android.view.View[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[2]/android.widget.Button[1]";

        /** "report_Menu_Help" String in "Report". */
        public static final String report_Menu_Help ="//android.view.View[1]/android.widget.FrameLayout[2]/android.view.View[1]/android.widget.RelativeLayout[1]/android.widget.ScrollView[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[3]/android.widget.LinearLayout[1]/android.widget.Button[1]";
    }

    /** "Search" Component and its children. */
    public static class Search {

        // No use for a default constructor.
        private Search(){}

        /** "Search" Window Component itself. */
        public static final String Search = new String("Search");

        /** "search_Filter_Date_In_24_Hour" String in "Search". */
        public static final String search_Filter_Date_In_24_Hour ="//android.view.View[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[2]/android.widget.ImageButton[1]";

        /** "search_Filter_Date_All" String in "Search". */
        public static final String search_Filter_Date_All ="//android.view.View[1]/android.widget.FrameLayout[2]/android.view.View[1]/android.widget.RelativeLayout[1]/android.widget.ScrollView[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[1]/android.widget.Button[1]";

        /** "search_Filter_Location_InServer_2" String in "Search". */
        public static final String search_Filter_Location_InServer_2 ="//android.view.View[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[3]/android.widget.TextView[3]";

        /** "search_Filter_Location_InServer_1" String in "Search". */
        public static final String search_Filter_Location_InServer_1 ="//android.view.View[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[1]";

        /** "search_Filter_Date_Last_Month" String in "Search". */
        public static final String search_Filter_Date_Last_Month ="//android.widget.ListView[1]/android.widget.CheckedTextView[1]";

        /** "search_Box" String in "Search". */
        public static final String search_Box ="//android.widget.ListView[1]/android.widget.LinearLayout[1]/android.widget.RelativeLayout[1]/android.widget.TextView[1]";

        /** "search_Filter_Location_All" String in "Search". */
        public static final String search_Filter_Location_All ="//android.view.View[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[3]/android.widget.TextView[2]";

        /** "search_Filter_Date_Last_Week" String in "Search". */
        public static final String search_Filter_Date_Last_Week ="//android.view.View[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]";

        /** "search_Filter" String in "Search". */
        public static final String search_Filter ="//android.view.View[1]/android.widget.FrameLayout[2]/android.view.View[1]/android.widget.RelativeLayout[1]/android.widget.ScrollView[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[2]/android.widget.LinearLayout[1]/android.widget.Button[1]";
    }

    /** "NaviBar" Component and its children. */
    public static class NaviBar {

        // No use for a default constructor.
        private NaviBar(){}

        /** "NaviBar" Window Component itself. */
        public static final String NaviBar = new String("NaviBar");

        /** "navi_Settings" String in "NaviBar". */
        public static final String navi_Settings ="//android.view.View[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[2]/android.widget.ImageButton[1]";

        /** "navi_Search" String in "NaviBar". */
        public static final String navi_Search ="//android.view.View[1]/android.widget.FrameLayout[2]/android.view.View[1]/android.widget.RelativeLayout[1]/android.widget.ScrollView[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[1]/android.widget.Button[1]";

        /** "navi_Portfolio" String in "NaviBar". */
        public static final String navi_Portfolio ="//android.view.View[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[3]/android.widget.TextView[3]";

        /** "navi_Library" String in "NaviBar". */
        public static final String navi_Library ="//android.view.View[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[1]";

        /** "navigator" String in "NaviBar". */
        public static final String navi_Menu ="//android.widget.ListView[1]/android.widget.CheckedTextView[1]";
      
        /** "navi_Help" String in "NaviBar". */
        public static final String navi_Help ="//android.widget.ListView[1]/android.widget.LinearLayout[1]/android.widget.RelativeLayout[1]/android.widget.TextView[1]";
    }

    /** "SeeAll" Component and its children. */
    public static class SeeAll {

        // No use for a default constructor.
        private SeeAll(){}

        /** "SeeAll" Window Component itself. */
        public static final String SeeAll = new String("SeeAll");

        /** "seeAll_Subscribed" String in "SeeAll". */
        public static final String seeAll_Subscribed ="//android.view.View[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[2]/android.widget.ImageButton[1]";

        /** "seeAll_Subscribed_Report_Selected_Delete" String in "SeeAll". */
        public static final String seeAll_Subscribed_Report_Selected_Delete ="//android.view.View[1]/android.widget.FrameLayout[2]/android.view.View[1]/android.widget.RelativeLayout[1]/android.widget.ScrollView[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[1]/android.widget.Button[1]";

        /** "seeAll_Subscribed_Report_Selected_Finish" String in "SeeAll". */
        public static final String seeAll_Subscribed_Report_Selected_Finish ="//android.view.View[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[3]/android.widget.TextView[3]";

        /** "seeAll_Subscribed_Report_Selected_Cancel" String in "SeeAll". */
        public static final String seeAll_Subscribed_Report_Selected_Cancel ="//android.view.View[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[1]";

        /** "seeAll_Subscribed_Menu_Select" String in "SeeAll". */
        public static final String seeAll_Subscribed_Menu_Select ="//android.widget.ListView[1]/android.widget.CheckedTextView[1]";

        /** "seeAll_Subscribed_Report_Selected_Share" String in "SeeAll". */
        public static final String seeAll_Subscribed_Report_Selected_Share ="//android.widget.ListView[1]/android.widget.LinearLayout[1]/android.widget.RelativeLayout[1]/android.widget.TextView[1]";

        /** "seeAll_Recent_NaviUp" String in "SeeAll". */
        public static final String seeAll_Recent_NaviUp ="//android.view.View[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[3]/android.widget.TextView[2]";

        /** "seeAll_Recent" String in "SeeAll". */
        public static final String seeAll_Recent ="//android.view.View[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]";

        /** "seeAll_Subscribed_Report_Selected_Add_To_Favorite" String in "SeeAll". */
        public static final String seeAll_Subscribed_Report_Selected_Add_To_Favorite ="//android.view.View[1]/android.widget.FrameLayout[2]/android.view.View[1]/android.widget.RelativeLayout[1]/android.widget.ScrollView[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[2]/android.widget.LinearLayout[1]/android.widget.Button[1]";

        /** "seeAll_Subscribed_NaviUp" String in "SeeAll". */
        public static final String seeAll_Subscribed_NaviUp ="//android.view.View[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[3]/android.widget.TextView[1]";

        /** "seeAll_Subscribed_Report_Selected_Selected_Count" String in "SeeAll". */
        public static final String seeAll_Subscribed_Report_Selected_Selected_Count ="//android.view.View[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[2]/android.widget.Button[1]";

        /** "seeAll_Favorites" String in "SeeAll". */
        public static final String seeAll_Favorites ="//android.view.View[1]/android.widget.FrameLayout[2]/android.view.View[1]/android.widget.RelativeLayout[1]/android.widget.ScrollView[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[3]/android.widget.LinearLayout[1]/android.widget.Button[1]";

        /** "seeAll_Recent_Menu" String in "SeeAll". */
        public static final String seeAll_Recent_Menu ="//android.view.View[1]/android.widget.FrameLayout[2]/android.widget.LinearLayout[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[1]/android.widget.Spinner[1]";

        /** "seeAll_SortBy" String in "SeeAll". */
        public static final String seeAll_SortBy ="//android.view.View[1]/android.widget.FrameLayout[2]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.view.View[1]/android.widget.Button[2]";

        /** "seeAll_Subscribed_Menu" String in "SeeAll". */
        public static final String seeAll_Subscribed_Menu ="//android.view.View[1]/android.widget.FrameLayout[2]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.ScrollView[1]/android.widget.TableLayout[1]/android.widget.TableRow[5]/android.widget.EditText[1]";
    }

    /** "Settings" Component and its children. */
    public static class Settings {

        // No use for a default constructor.
        private Settings(){}

        /** "Settings" Window Component itself. */
        public static final String Settings = new String("Settings");

        /** "settings_Add_Server_Window_1_Next" String in "Settings". */
        public static final String settings_Add_Server_Window_1_Next ="//android.view.View[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[2]/android.widget.ImageButton[1]";

        /** "settings_Add_Server_Window_2_Password" String in "Settings". */
        public static final String settings_Add_Server_Window_2_Password ="//android.view.View[1]/android.widget.FrameLayout[2]/android.view.View[1]/android.widget.RelativeLayout[1]/android.widget.ScrollView[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[1]/android.widget.Button[1]";

        /** "settings_Server_Detail_Item_ServerDebugging" String in "Settings". */
        public static final String settings_Server_Detail_Item_ServerDebugging ="//android.view.View[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[3]/android.widget.TextView[3]";

        /** "settings_Add_Server_Window_3_OK" String in "Settings". */
        public static final String settings_Add_Server_Window_3_OK ="//android.view.View[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[1]";

        /** "settings_Add_Server_Window_2_Cancel" String in "Settings". */
        public static final String settings_Add_Server_Window_2_Cancel ="//android.widget.ListView[1]/android.widget.CheckedTextView[1]";

        /** "settings_Add_Server_Window_1_ServerPort" String in "Settings". */
        public static final String settings_Add_Server_Window_1_ServerPort ="//android.widget.ListView[1]/android.widget.LinearLayout[1]/android.widget.RelativeLayout[1]/android.widget.TextView[1]";

        /** "settings_Add_Server_Window_1_ServerName" String in "Settings". */
        public static final String settings_Add_Server_Window_1_ServerName ="//android.view.View[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[3]/android.widget.TextView[2]";

        /** "settings_Add_Server_Window_2_Next" String in "Settings". */
        public static final String settings_Add_Server_Window_2_Next ="//android.view.View[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]";

        /** "settings_Server_Detail_Item_RemoveConnection" String in "Settings". */
        public static final String settings_Server_Detail_Item_RemoveConnection ="//android.view.View[1]/android.widget.FrameLayout[2]/android.view.View[1]/android.widget.RelativeLayout[1]/android.widget.ScrollView[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[2]/android.widget.LinearLayout[1]/android.widget.Button[1]";

        /** "settings_Add_Server_Window_2_UID" String in "Settings". */
        public static final String settings_Add_Server_Window_2_UID ="//android.view.View[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[3]/android.widget.TextView[1]";

        /** "settings_Add_Connection" String in "Settings". */
        public static final String settings_Add_Connection ="//android.view.View[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[2]/android.widget.Button[1]";

        /** "settings_Server_Detail_Item_Description" String in "Settings". */
        public static final String settings_Server_Detail_Item_Description ="//android.view.View[1]/android.widget.FrameLayout[2]/android.view.View[1]/android.widget.RelativeLayout[1]/android.widget.ScrollView[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[3]/android.widget.LinearLayout[1]/android.widget.Button[1]";

        /** "settings_Add_Server_Window_1_ServerSecurityBox" String in "Settings". */
        public static final String settings_Add_Server_Window_1_ServerSecurityBox ="//android.view.View[1]/android.widget.FrameLayout[2]/android.widget.LinearLayout[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[1]/android.widget.Spinner[1]";

        /** "settings_Add_Server_Window_2_LogonAsGuest" String in "Settings". */
        public static final String settings_Add_Server_Window_2_LogonAsGuest ="//android.view.View[1]/android.widget.FrameLayout[2]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.view.View[1]/android.widget.Button[2]";

        /** "settings_Add_Server_Window_1_Cancel" String in "Settings". */
        public static final String settings_Add_Server_Window_1_Cancel ="//android.view.View[1]/android.widget.FrameLayout[2]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.ScrollView[1]/android.widget.TableLayout[1]/android.widget.TableRow[5]/android.widget.EditText[1]";

        /** "settings_Server_Detail_Item_ClearHistory" String in "Settings". */
        public static final String settings_Server_Detail_Item_ClearHistory ="//android.view.View[1]/android.widget.FrameLayout[2]/android.widget.LinearLayout[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[1]/android.widget.Spinner[5]";
    }

    /** "Library" Component and its children. */
    public static class Library {

        // No use for a default constructor.
        private Library(){}

        /** "Library" Window Component itself. */
        public static final String Library = new String("Library");

        /** "library_Menu" String in "Library". */
        public static final String library_Menu ="//android.view.View[1]/android.widget.FrameLayout[1]/android.view.View[1]/android.widget.LinearLayout[2]/android.widget.ImageButton[1]";
    }
}
